apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic
  labels:
    tipo: desarrollo
spec:
  selector:
    matchLabels:
      app: elastic
  replicas: 2
  strategy:
    type: RollingUpdate
  minReadySeconds: 2
  template:
    metadata:
      labels:
        app: elastic
    spec:
      containers:
      - name: elastic
        image: elastic/elasticsearch:8.18.8
        ports:
        - containerPort: 9200